"""Single-host a13n checkpoints; the host owns effect reconciliation.

This store deliberately does not recover workers or replay tool calls. Linux
flock serializes one conversation across processes. An unfinished journal must
be reconciled by the operator before another worker may enter that thread.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import os
import tempfile
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any


class A13nStateStore:
    def __init__(self, root: str | Path) -> None:
        self.root = Path(root)

    def directory(self, thread_id: str) -> Path:
        # Both identifiers are generated by the host, never worker paths.
        if not thread_id.startswith("bot_") or len(thread_id) != 68 or any(c not in "0123456789abcdef" for c in thread_id[4:]):
            raise ValueError("invalid a13n thread identifier")
        directory = self.root / thread_id
        missing = []
        ancestor = directory.absolute()
        while not ancestor.exists():
            missing.append(ancestor)
            ancestor = ancestor.parent
        for path in reversed(missing):
            path.mkdir(exist_ok=True, mode=0o700)
            # Persist newly created ancestry before any effect can be dispatched.
            # Fsync of a file's own directory does not persist its parent's entry.
            self._sync_directory(path.parent)
        os.chmod(self.root, 0o700)
        os.chmod(directory, 0o700)
        return directory

    @staticmethod
    def _sync_directory(directory: Path) -> None:
        descriptor = os.open(directory, os.O_RDONLY)
        try:
            os.fsync(descriptor)
        finally:
            os.close(descriptor)

    @asynccontextmanager
    async def lock(self, thread_id: str):
        import fcntl  # Explicitly a Linux/POSIX single-host store.

        path = self.directory(thread_id) / "thread.lock"
        descriptor = os.open(path, os.O_CREAT | os.O_RDWR, 0o600)
        try:
            os.fchmod(descriptor, 0o600)
            while True:
                try:
                    fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
                    break
                except BlockingIOError:
                    await asyncio.sleep(0.05)
            yield
        finally:
            fcntl.flock(descriptor, fcntl.LOCK_UN)
            os.close(descriptor)

    def read(self, thread_id: str, filename: str) -> dict[str, Any] | None:
        path = self.directory(thread_id) / filename
        if not path.exists():
            return None
        if path.stat().st_size > 32 * 1024 * 1024:
            raise ValueError("a13n state exceeds storage limit")
        value = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(value, dict):
            raise ValueError("a13n state must be an object")
        return value

    def write(self, thread_id: str, filename: str, value: dict[str, Any]) -> None:
        directory = self.directory(thread_id)
        serialized = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
        if len(serialized.encode("utf-8")) > 32 * 1024 * 1024:
            raise ValueError("a13n state exceeds storage limit")
        descriptor, temporary = tempfile.mkstemp(prefix=".checkpoint-", dir=directory)
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
                os.fchmod(stream.fileno(), 0o600)
                stream.write(serialized)
                stream.flush()
                os.fsync(stream.fileno())
            os.replace(temporary, directory / filename)
            self._sync_directory(directory)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)

    @staticmethod
    def run_filename(run_id: str) -> str:
        return f"run-{hashlib.sha256(run_id.encode()).hexdigest()}.json"
