"""Harness foundation modules.

Phase 1 centralizes context-compaction policy.
Phase 2 starts extracting shared context/inbox pipeline helpers and loop policy.
"""

from app.harness.compaction import (
    DEFAULT_COMPACTION_AFTER_ROUND,
    DEFAULT_COMPACTION_KEEP_RECENT,
    compress_gemini_function_results,
    compress_openai_tool_results,
)
from app.harness.coding_workflow import (
    build_coding_workflow_instructions,
    is_coding_workflow_turn,
    should_clarify_before_coding,
    should_plan_before_coding,
)
from app.harness.context import (
    append_openai_inbox_messages,
    normalize_inbox_item,
)
from app.harness.common_knowledge import (
    CommonKnowledgeDecision,
    build_common_knowledge_search_block_message,
    classify_common_knowledge_turn,
    should_relax_common_knowledge_grounding,
)
from app.harness.control_plane import (
    ControlDecision,
    ControlEvent,
    PublicOutputDecision,
    append_openai_control_event,
    has_internal_control_leak,
    render_control_event,
    render_control_text,
    sanitize_public_reply,
)
from app.harness.grounding import (
    detect_evidence_contract_gap,
    build_grounding_nudge,
    build_temporal_grounding_nudge,
    detect_temporal_grounding_issue,
    reply_contains_dense_factual_claims,
    requires_temporal_grounding,
    requires_external_grounding,
    should_relax_fact_grounding,
)
from app.harness.orchestrator import (
    should_compact_history,
    should_nudge_unmatched_reads,
)
from app.harness.search_guardrails import (
    extract_focus_terms,
    is_fact_pack_query,
    is_opinion_query,
    is_query_off_topic,
    requires_fact_pack_first,
    is_temporal_scope_drift_query,
    rewrite_web_search_query,
)
from app.harness.session_facts import (
    ContinuationContext,
    build_continuation_context,
    infer_turn_objective,
    remember_active_constraints,
    remember_recent_topic,
    remember_visual_turn,
    should_reuse_active_constraints,
    should_reuse_recent_topic,
    should_reuse_recent_visual,
)
from app.harness.task_board import (
    PLAN_ACTIVE_STATUSES,
    advance_next_step,
    build_active_plan_context,
    format_plan_text,
    normalize_steps,
    prune_invalid_dependencies,
)
from app.harness.turn_mode import (
    TurnMode,
    has_explicit_code_intent,
    infer_turn_mode,
    is_non_actionable_turn,
    is_product_pricing_turn,
    sanitize_suggested_groups,
    should_run_code_preflight,
)
from app.harness.tool_escalation import (
    build_stable_common_knowledge_search_nudge,
    build_tool_domain_nudge,
    build_tool_settle_nudge,
    is_light_advice_turn,
)
from app.harness.tool_runtime import invoke_tool_handler
from app.harness.runtime_errors import (
    CODE_BUG,
    IGNORED,
    MANUAL_DIAGNOSTIC,
    NEEDS_TRIAGE,
    TRANSIENT_UPSTREAM,
    RuntimeErrorBatchDecision,
    RuntimeErrorDecision,
    classify_runtime_error,
    classify_runtime_error_batch,
)

__all__ = [
    "DEFAULT_COMPACTION_AFTER_ROUND",
    "DEFAULT_COMPACTION_KEEP_RECENT",
    "compress_gemini_function_results",
    "compress_openai_tool_results",
    "build_coding_workflow_instructions",
    "is_coding_workflow_turn",
    "should_clarify_before_coding",
    "should_plan_before_coding",
    "append_openai_inbox_messages",
    "normalize_inbox_item",
    "CommonKnowledgeDecision",
    "build_common_knowledge_search_block_message",
    "classify_common_knowledge_turn",
    "should_relax_common_knowledge_grounding",
    "ControlDecision",
    "ControlEvent",
    "PublicOutputDecision",
    "append_openai_control_event",
    "has_internal_control_leak",
    "render_control_event",
    "render_control_text",
    "sanitize_public_reply",
    "build_grounding_nudge",
    "detect_evidence_contract_gap",
    "build_temporal_grounding_nudge",
    "detect_temporal_grounding_issue",
    "reply_contains_dense_factual_claims",
    "requires_temporal_grounding",
    "requires_external_grounding",
    "should_relax_fact_grounding",
    "should_compact_history",
    "should_nudge_unmatched_reads",
    "extract_focus_terms",
    "is_fact_pack_query",
    "is_opinion_query",
    "is_query_off_topic",
    "requires_fact_pack_first",
    "is_temporal_scope_drift_query",
    "rewrite_web_search_query",
    "ContinuationContext",
    "build_continuation_context",
    "infer_turn_objective",
    "remember_active_constraints",
    "remember_recent_topic",
    "remember_visual_turn",
    "should_reuse_active_constraints",
    "should_reuse_recent_topic",
    "should_reuse_recent_visual",
    "PLAN_ACTIVE_STATUSES",
    "advance_next_step",
    "build_active_plan_context",
    "format_plan_text",
    "normalize_steps",
    "prune_invalid_dependencies",
    "TurnMode",
    "has_explicit_code_intent",
    "infer_turn_mode",
    "is_non_actionable_turn",
    "is_product_pricing_turn",
    "sanitize_suggested_groups",
    "should_run_code_preflight",
    "build_stable_common_knowledge_search_nudge",
    "build_tool_domain_nudge",
    "build_tool_settle_nudge",
    "is_light_advice_turn",
    "invoke_tool_handler",
    "CODE_BUG",
    "IGNORED",
    "MANUAL_DIAGNOSTIC",
    "NEEDS_TRIAGE",
    "TRANSIENT_UPSTREAM",
    "RuntimeErrorBatchDecision",
    "RuntimeErrorDecision",
    "classify_runtime_error",
    "classify_runtime_error_batch",
]
